"""update submission table

Revision ID: 2e1571b38603
Revises: 85bf42c8546e
Create Date: 2025-03-16 17:16:27.836756

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e1571b38603"
down_revision: Union[str, None] = "85bf42c8546e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission",
        sa.Column("feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_unique_constraint(None, "submission", ["participant_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "submission", type_="unique")
    op.drop_column("submission", "feedback")
    # ### end Alembic commands ###
