"""add paymentstatus enum

Revision ID: 300594f19f1a
Revises: a0bf516ac0c6
Create Date: 2025-03-15 17:17:22.647399

"""

from typing import Sequence, Union

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "300594f19f1a"
down_revision: Union[str, None] = "a0bf516ac0c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="paymentstatus",
        new_values=["PENDING", "PAID"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="payment", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="paymentstatus",
        new_values=["PENDING", "APPROVED", "REJECTED"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="payment", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
