"""use program id in submissions

Revision ID: 7c2dd8df02d2
Revises: 2e1571b38603
Create Date: 2025-03-19 00:36:28.067369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2dd8df02d2'
down_revision: Union[str, None] = '2e1571b38603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('submission_id', sa.Uuid(), nullable=False))
    op.add_column('payment', sa.Column('admin_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'payment', 'user', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'submission', ['submission_id'], ['id'])
    op.add_column('submission', sa.Column('program_id', sa.Uuid(), nullable=False))
    op.drop_constraint('submission_participant_id_key', 'submission', type_='unique')
    op.create_unique_constraint(None, 'submission', ['program_id'])
    op.drop_constraint('submission_participant_id_fkey', 'submission', type_='foreignkey')
    op.create_foreign_key(None, 'submission', 'bountyprogram', ['program_id'], ['id'])
    op.drop_column('submission', 'participant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('participant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.create_foreign_key('submission_participant_id_fkey', 'submission', 'participant', ['participant_id'], ['id'])
    op.drop_constraint(None, 'submission', type_='unique')
    op.create_unique_constraint('submission_participant_id_key', 'submission', ['participant_id'])
    op.drop_column('submission', 'program_id')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'admin_id')
    op.drop_column('payment', 'submission_id')
    # ### end Alembic commands ###
