"""remove participant name unqiue

Revision ID: 85bf42c8546e
Revises: 300594f19f1a
Create Date: 2025-03-16 15:56:03.754271

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85bf42c8546e"
down_revision: Union[str, None] = "300594f19f1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('bountyprogram_name_key', 'bountyprogram', type_='unique')
    # op.drop_constraint('submission_participant_id_key', 'submission', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("submission_participant_id_key", "submission", ["participant_id"])
    op.create_unique_constraint("bountyprogram_name_key", "bountyprogram", ["name"])
    # ### end Alembic commands ###
