"""remove unique constriant from submission

Revision ID: 9db4a05fc902
Revises: ff5a98e6d468
Create Date: 2025-03-19 23:59:31.359387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db4a05fc902'
down_revision: Union[str, None] = 'ff5a98e6d468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submission_program_id_key', 'submission', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('submission_program_id_key', 'submission', ['program_id'])
    # ### end Alembic commands ###
