"""add on delete cascade for tables

Revision ID: ff5a98e6d468
Revises: 7c2dd8df02d2
Create Date: 2025-03-19 01:46:52.119159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5a98e6d468'
down_revision: Union[str, None] = '7c2dd8df02d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bountyprogram_owner_id_fkey', 'bountyprogram', type_='foreignkey')
    op.create_foreign_key(None, 'bountyprogram', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('participant_program_id_fkey', 'participant', type_='foreignkey')
    op.drop_constraint('participant_hacker_id_fkey', 'participant', type_='foreignkey')
    op.create_foreign_key(None, 'participant', 'bountyprogram', ['program_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'participant', 'user', ['hacker_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('payment_submission_id_fkey', 'payment', type_='foreignkey')
    op.drop_constraint('payment_admin_id_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'submission', ['submission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payment', 'user', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('submission_updater_id_fkey', 'submission', type_='foreignkey')
    op.drop_constraint('submission_hacker_id_fkey', 'submission', type_='foreignkey')
    op.drop_constraint('submission_program_id_fkey', 'submission', type_='foreignkey')
    op.create_foreign_key(None, 'submission', 'user', ['updater_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submission', 'user', ['hacker_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submission', 'bountyprogram', ['program_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.create_foreign_key('submission_program_id_fkey', 'submission', 'bountyprogram', ['program_id'], ['id'])
    op.create_foreign_key('submission_hacker_id_fkey', 'submission', 'user', ['hacker_id'], ['id'])
    op.create_foreign_key('submission_updater_id_fkey', 'submission', 'user', ['updater_id'], ['id'])
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key('payment_admin_id_fkey', 'payment', 'user', ['admin_id'], ['id'])
    op.create_foreign_key('payment_submission_id_fkey', 'payment', 'submission', ['submission_id'], ['id'])
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.create_foreign_key('participant_hacker_id_fkey', 'participant', 'user', ['hacker_id'], ['id'])
    op.create_foreign_key('participant_program_id_fkey', 'participant', 'bountyprogram', ['program_id'], ['id'])
    op.drop_constraint(None, 'bountyprogram', type_='foreignkey')
    op.create_foreign_key('bountyprogram_owner_id_fkey', 'bountyprogram', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
